### ISSUE TITLE
Error when trying to install background on mac

### ISSUE THREAD

**Issue by samd1993** [KatsuteDev/Background#62] opened 2022-11-17 18:17 UTC
### Operating System

macOS

### VSCode Version

1.70.1 

### Extension Version

v1.1.0

### Issue

When I run Background:Install in command pallette I get this error from Mac:

Command 'Background: Install' resulted in an error (A system error occurred (EROFS: read-only file system, open '/private/var/folders/lg/dnk04c613yn9h0pk51fgy97c0000gn/T/AppTranslocation/22C18D79-D2CC-467C-8AA1-80126B0C0910/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-window.js'))

Any ideas?

### How to replicate

I installed the extension from Windows store..then added image from Downloads folder in the Background:Configuration setttings..a message popped up saying resintall required and I clicked ok...nothing happened. Then I closed Vscode and opened again and tried Background:Install

Any idea?

**Comment by Katsute** [comment] 2022-11-20 03:09
Seems to be an issue with VSCode installing with read-only permissions, I will try and see if I can remove this protection so the extension will work.

`fs.chmodSync`

https://nodejs.org/api/fs.html

**Comment by Katsute** [comment] 2022-12-06 03:22
This issue may or may not have been fixed by #64, I don't have a mac to test this on so please let me know if this issue still occurs.

Alternatively: Open shell and use `chown -R +rwx "Visual Studio Code.app"` in the directory where visual studio code is installed.

**Comment by samd1993** [comment] 2022-12-14 22:24
Hi,

I tried reinstalling it but get this error when I do the Background Install command:

`Command 'Background: Install' resulted in an error (A system error occurred (EROFS: read-only file system, open '/private/var/folders/lg/dnk04c613yn9h0pk51fgy97c0000gn/T/AppTranslocation/22C18D79-D2CC-467C-8AA1-80126B0C0910/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-window.js'))`

**Comment by Katsute** [comment] 2022-12-15 20:17
Seems to be a bug caused by https://github.com/microsoft/vscode/issues/7426.

Try moving vscode from the `Download` to the `Application` directory. https://github.com/microsoft/vscode/issues/7426#issuecomment-425093469

If that doesn't work try running `sudo chmod -R a+rwx 'Visual Studio Code.app'` in the directory where vscode is installed.

Let me know if any of those fixes work, I can't test these because I don't have a mac.

**Comment by Katsute** [comment] 2022-12-15 20:23
Did you try `sudo chmod -R a+rwx 'Visual Studio Code.app'`?

**Comment by samd1993** [comment] 2022-12-15 20:24
oops I tried the correct code and for some reason my application folder is empty?

(```
base) samd@Sams-MacBook-Air-7 Applications % sudo chmod -R a+rwx 'Visual Studio Code.app'
Password:
chmod: Visual Studio Code.app: No such file or directory
(base) samd@Sams-MacBook-Air-7 Applications % ls
(base) samd@Sams-MacBook-Air-7 Applications % pwd
/Users/samd/Applications
(base) samd@Sams-MacBook-Air-7 Applications % ls
(base) samd@Sams-MacBook-Air-7 Applications % 
```

**Comment by samd1993** [comment] 2022-12-15 20:29
Ok fixed it and was able to run code successfully. However I still get same error. I also tried reinstalling package and restarting vscode as well

**Comment by Katsute** [comment] 2022-12-15 20:31
Try with `sudo chmod -R a+rwx '/Applications/Visual Studio Code.app'`, maybe explicitly specifying `/Applications/` will see it.

**Comment by samd1993** [comment] 2022-12-15 20:32
OK SO  I had to force quit Vscode and restart and then it works! Thanks for the help :)

**Comment by Katsute** [comment] 2022-12-15 20:33
Just to make sure, the one with the `/Applications/` added works or the one before?

**Comment by samd1993** [comment] 2022-12-15 20:38
The one before worked... BUT i had already went to /Applications where the slash is in front so I am guessing the /Applications will work as well

Last question: is there a reason I am seeing a double image? If i do opacity of 0.1 it looks fine but then when i increase to 0.5 there are two duplicate backgrounds that are slightly offset making a very blurry background

**Comment by Katsute** [comment] 2022-12-15 20:40
Double image might be caused by you having images set for both the window and editor at the same time.

**Closed** 2022-12-15 22:37 UTC
Labels: critical bug, help wanted, vscode, macos
