### ISSUE TITLE
VS Code unusable, background opacity 100%

### ISSUE THREAD

**Issue by 9winged** [KatsuteDev/Background#432] opened 2024-12-12 12:38 UTC
### Checks

- [x] I have checked [existing issues](https://github.com/KatsuteDev/Background/issues?q=is%3Aissue+is%3Aopen+label%3Abug%2C%22critical+bug%22).
- [x] I have checked the [help page](https://github.com/KatsuteDev/Background/blob/main/HELP.md).
- [x] This is actually a bug and not a feature.
- [x] I am using the latest extension version.

### Operating System

Win 11

### VSCode Version

1.96

### Extension Version

latest

### Settings

Read Issue Tab, can't acces anything inside the editor. Couldn't find settings.json in my .vscode folder.

### Settings Verification

- [x] I have made sure to remove any sensitive or personal information from the above input.

### Issue

I chose a window background and now it's on 100% opacity. Can't see anything in my VS Code anymore. I've tried to delete the extension through \.vscode\extensions folder. But seems that the background still there with 100% opacity. Have to reinstall VS Code now ._. 

(Picture is VS Code)

### How to replicate

![Image](https://github.com/user-attachments/assets/05d891d1-7f26-4cb0-970c-44069935ecaa)

**Comment by 9winged** [comment] 2024-12-12 12:51
![Image](https://github.com/user-attachments/assets/e5926360-ae9e-4191-91be-f054654ec0c5)


After reinstalling with another picture, same issue.

**Comment by Katsute** [comment] 2024-12-12 13:09
The background opacity may be set too high, use a lower percentage.

**Comment by 9winged** [comment] 2024-12-12 13:12
"background.backgroundOpacity": [
        0.01,
        0.1,
        0.1,
        0.01
    ],
    "background.backgroundBlur": [
        "0",
        "0",
        "0",
        "800"
    ],

I could access the setting.json

which one do I have to turn donw?

**Comment by 9winged** [comment] 2024-12-12 13:16
okay got it know, but it looks kinda funny. Its all transparent.

![Image](https://github.com/user-attachments/assets/980861e7-5a6d-42d6-a3d9-9ab5ca5c8e25)

**Comment by 9winged** [comment] 2024-12-12 13:18
alright I've tried it with another picture and it works perfectly now

**Comment by 9winged** [comment] 2024-12-12 13:23
okay, now it changes between the old and new pic after every change to opacity and blur xD and also the same as before. Set opacity to 0.99 and its on 90% opacity.

Do you need any files that can help you ?

**Comment by Katsute** [comment] 2024-12-12 14:01
> okay got it know, but it looks kinda funny. Its all transparent.
> 
> ![Image](https://github.com/user-attachments/assets/980861e7-5a6d-42d6-a3d9-9ab5ca5c8e25)
> 

the one in this screenshot is the intended behavior, the transparency is needed so you can see the ui, there is no option to have both the background and ui be 100% visible

**Comment by 9winged** [comment] 2024-12-12 14:05
Alright, right now nothing changes if I change the opacity settings. It stays the same. It is slightly visible. 

![Image](https://github.com/user-attachments/assets/06e5528b-6b88-409a-9e20-5b985455c760)

**Comment by Katsute** [comment] 2024-12-12 14:13
you need to run the background install command for any config changes to take effect

**Comment by Katsute** [comment] 2024-12-12 22:59
When using an out of range opacity the following error is usually shown:

![Image](https://github.com/user-attachments/assets/2996a78c-ff44-4219-b923-2ee2c9b30c7f)

The only case this isn't shown is when you toggle the inverted opacity option when you have an opacity already set, which can cause a normally safe opacity to become too low.

![Image](https://github.com/user-attachments/assets/3d0af02b-c8f5-46b0-9a65-8eb2fb6b33ce)

You can reset the opacity setting to default to the recommended value based on the current settings:

![Image](https://github.com/user-attachments/assets/76c48164-2b22-4615-9fad-f8216dbc5719)

Closing this issue as this is intended behavior, if you encounter any other issues with the extension, you can use the 'Report an issue' option in the extension which will open a bug report with the background settings prefilled.

**Closed by Katsute** 2024-12-12 22:59 UTC
Labels: bug
