### ISSUE TITLE
Installation doesn't work. No prompt for admin permission. 

### ISSUE THREAD

**Issue by tiritto** [KatsuteDev/Background#113] opened 2023-03-04 22:44 UTC
### Operating System

Linux - Nobara 37 _(derivative of Fedora 37_)

### VSCode Version

1.76.0

### Extension Version

2.5.0

### Issue

Installing extensions via "Background: Install" doesn't work. In fact, it feels as if the option itself doesn't do anything at all, as there is no feedback notification or anything that happens after pressing it.

The issue might be somewhat OS-related, because it works just perfectly fine on my other PC with Windows, running the same version of VSCode as my Linux machine. My VSCode installation on Linux is installed via official VSCode repository [mentioned on the official setup page](https://code.visualstudio.com/docs/setup/linux) for VSCode, so the issue is not Flatpak/Snap-related.

- I've tried to reinstall the extension, making sure to use use "Background: Uninstall" and restarting VSCode.
- I've disabled all other extensions to make sure that there are no conflicts, but it didn't affect the issue.

It might be useful to mention that when I later decided to try out another background changing extension (`shalldie.background`) it worked just fine - I've got a proper prompt and everything worked as expected. Maybe this will provide some hint regarding cause of the issue.

### How to replicate

Just install the extension and attempt to run `Background: Install:`

**Comment by Katsute** [comment] 2023-03-04 22:54
Most likely caused by these functions:

https://github.com/KatsuteDev/Background/blob/8bc13162af5c467499471d01ab466bf455ff99a7/src/extension.ts#L133-L135

https://github.com/KatsuteDev/Background/blob/8bc13162af5c467499471d01ab466bf455ff99a7/src/extension.ts#L113-L120

Should be fixed by using a try-catch on the write

**Closed** 2023-03-05 21:55 UTC
Labels: critical bug, high priority, vscode, macos, linux
